name: receipt_reader
description: A Flutter package for reading and processing receipts using Google ML Kit.
version: 0.0.7
homepage: https://github.com/KanyantaM/receipt_reader # Add your GitHub repo or website here

repository: https://github.com/KanyantaM/receipt_reader # Update with your GitHub repo
issue_tracker: https://github.com/KanyantaM/receipt_reader/issues # GitHub issue tracker

environment:
  sdk: '>=3.5.0 <4.0.0' # Ensure compatibility with Dart SDK versions
  flutter: ">=2.5.0" # Flutter SDK compatibility

dependencies:
  flutter:
    sdk: flutter
  # ML Kit for recognizing text from receipts.
  google_mlkit_text_recognition: ^0.14.0

  # Image picker for selecting receipt images from the gallery or camera.
  image_picker: ^1.1.2
  
  # Path provider for storing and retrieving receipt images from the local filesystem.
  path_provider: ^2.1.4
  google_generative_ai: ^0.4.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Lints for maintaining code quality.
  flutter_lints: ^5.0.0
  
  # Mockito for creating mock objects in unit tests.
  mockito: ^5.4.4
  
  # Build runner for code generation in tests.
  build_runner: ^2.4.13

# Uncomment the following lines if your package uses assets or fonts
# flutter:
#   assets:
#     - assets/sample_receipt.jpg # Sample receipt image for testing or demo purposes

#   fonts:
#     - family: CustomFont
#       fonts:
#         - asset: fonts/CustomFont-Regular.ttf
#         - asset: fonts/CustomFont-Bold.ttf
#           weight: 700
